### ISSUE TITLE
binance.client get /fapi/v1/positionrisk is retired  please use GET /fapi/v2/positionRisk

### ISSUE THREAD

**Issue by layalihamam** [binance/binance-futures-connector-python#130]
I am using `binance.client` and each time i turn on my bot to place position and order i get this error:
 `Exception in thread Thread-1 (f1):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pro\Downloads\try888\main.py", line 8, in f1
    bot1.run()
  File "C:\Users\pro\Downloads\try888\classes.py", line 133, in run
    x = client.futures_position_information(symbol=self.symbol)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 6327, in futures_position_information
    return self._request_futures_api('get', 'positionRisk', True, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 382, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 358, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 367, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-5000): GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk`

i have updated the files in my binance folder and it's the same error

**Comment by 2pd** [comment]
`GET /fapi/v1/positionrisk` is not used in this library. Please upgrade to `/fapi/v2/positionrisk` in your code as the error message required.
